# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56b819343713ef37d500196acb430614f09358bbc8c1a291a72201f83ae1e73778f3ea3f117b8b1494729c46b8556449589b5f647d3e2c5e5c8cd3eea9778d0a

test:
  secret_key_base: 1df1a67d2cbe58c4d476dad43c43be067f6847571c62bb22751d52e3d5e84e91e1ec6c1a70ec1f3dec4b7035ee2196f98c6a994752a38d9c9b318e5c9d430d5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
